// ============================================================================
// NGO-Guardian — Report Generator
// Generates vibe-check-report.md and fix-artifact.patch for Person B handoff
// ============================================================================

import { writeFileSync, mkdirSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const PROJECT_ROOT = join(__dirname, "..", "..");

/**
 * Generate the Vibe Check Report (Markdown)
 */
export function generateVibeCheckReport(scoredTargets) {
  const timestamp = new Date().toISOString();
  let md = "";

  md += `# 🛡️ NGO-Guardian — Vibe Check Report\n\n`;
  md += `> **Generated**: ${timestamp}\n`;
  md += `> **Scanned Targets**: ${scoredTargets.length}\n`;
  md += `> **Pipeline**: Discovery → Fingerprint → Scan → Score\n\n`;
  md += `---\n\n`;

  // Executive Summary
  const totalVulns = scoredTargets.reduce((s, t) => s + t.scan.counts.total, 0);
  const totalCritical = scoredTargets.reduce((s, t) => s + t.scan.counts.critical, 0);
  const avgScore = Math.round(scoredTargets.reduce((s, t) => s + t.scoring.vibeRiskScore, 0) / scoredTargets.length);

  md += `## 📋 Executive Summary\n\n`;
  md += `| Metric | Value |\n`;
  md += `|--------|-------|\n`;
  md += `| Total Targets Scanned | ${scoredTargets.length} |\n`;
  md += `| Total Vulnerabilities | ${totalVulns} |\n`;
  md += `| Critical Findings | ${totalCritical} |\n`;
  md += `| Average Vibe Risk Score | ${avgScore}/100 |\n\n`;

  // Risk Ranking
  md += `## 🏆 Risk Ranking\n\n`;
  md += `| Rank | Organization | Score | Risk Level | Critical |\n`;
  md += `|------|-------------|-------|------------|----------|\n`;

  scoredTargets.forEach((t, i) => {
    md += `| ${i + 1} | ${t.name} | ${t.scoring.vibeRiskScore}/100 | ${t.scoring.riskLevel} | ${t.scan.counts.critical} |\n`;
  });

  md += `\n---\n\n`;

  // Per-target detailed findings
  for (const target of scoredTargets) {
    md += `## 🔍 ${target.name}\n\n`;
    md += `- **Domain**: \`${target.domain}\`\n`;
    md += `- **Sector**: ${target.sector}\n`;
    md += `- **Mission**: ${target.mission}\n`;
    md += `- **Tech Stack**: ${target.fingerprint?.vibeStack?.platform || "Unknown"} + ${target.fingerprint?.vibeStack?.framework || "Unknown"}\n`;
    md += `- **Vibe Risk Score**: **${target.scoring.vibeRiskScore}/100** ${target.scoring.riskLevel}\n`;
    md += `- **Security Header Coverage**: ${target.fingerprint?.headerScore || "N/A"}%\n\n`;

    if (target.scoring.criticalDataExposure) {
      md += `> ⚠️ **CRITICAL DATA AT RISK** — This organization handles sensitive data that may be exposed.\n\n`;

      for (const d of target.scoring.exposedDataTypes.filter(d => d.level === "CRITICAL")) {
        md += `> - **${d.type}**: ${d.examples}\n`;
      }
      md += `\n`;
    }

    // Subdomains
    md += `### Subdomains\n\n`;
    for (const sub of target.subdomains) {
      md += `- \`${sub}\`\n`;
    }
    md += `\n`;

    // Vulnerabilities
    md += `### Findings\n\n`;

    const sortedVulns = [...target.scan.vulnerabilities].sort((a, b) => {
      const order = { CRITICAL: 0, HIGH: 1, MEDIUM: 2, LOW: 3 };
      return (order[a.severity] ?? 4) - (order[b.severity] ?? 4);
    });

    for (const vuln of sortedVulns) {
      const icon = { CRITICAL: "🔴", HIGH: "🟠", MEDIUM: "🟡", LOW: "⚪" }[vuln.severity] || "⚪";
      md += `#### ${icon} [${vuln.severity}] ${vuln.title} (${vuln.id})\n\n`;
      md += `- **Category**: ${vuln.category}\n`;
      md += `- **CWE**: ${vuln.cwe}\n`;
      md += `- **Location**: \`${vuln.location}\`\n`;
      md += `- **Description**: ${vuln.description}\n`;
      md += `- **Remediation**: ${vuln.remediation}\n\n`;
    }

    // Missing security headers
    if (target.fingerprint?.securityHeaders?.missing?.length > 0) {
      md += `### Missing Security Headers\n\n`;
      md += `| Header | Importance | Description |\n`;
      md += `|--------|-----------|-------------|\n`;
      for (const h of target.fingerprint.securityHeaders.missing) {
        md += `| \`${h.name}\` | ${h.importance} | ${h.description} |\n`;
      }
      md += `\n`;
    }

    md += `---\n\n`;
  }

  // Footer
  md += `## 🤝 About This Report\n\n`;
  md += `This report was generated by **NGO-Guardian**, a social-impact security platform.\n`;
  md += `We are "Guardians," not "Hunters." Our mission is to help under-resourced organizations\n`;
  md += `protect their digital infrastructure and the vulnerable data they steward.\n\n`;
  md += `> **Ethical Commitment**: Zero-exploitation. Privacy-first. Empathy always.\n\n`;
  md += `*For questions or support with remediation, please contact the NGO-Guardian team.*\n`;

  return md;
}

/**
 * Generate the Fix Artifact (patch-style remediation guide)
 */
export function generateFixArtifact(scoredTargets) {
  const timestamp = new Date().toISOString();
  let patch = "";

  patch += `# NGO-Guardian — Fix Artifact\n`;
  patch += `# Generated: ${timestamp}\n`;
  patch += `# This file contains actionable remediation steps for each finding.\n`;
  patch += `# Priority: CRITICAL → HIGH → MEDIUM → LOW\n\n`;

  for (const target of scoredTargets) {
    patch += `${"=".repeat(80)}\n`;
    patch += `# TARGET: ${target.name} (${target.domain})\n`;
    patch += `# Vibe Risk Score: ${target.scoring.vibeRiskScore}/100\n`;
    patch += `${"=".repeat(80)}\n\n`;

    const sortedVulns = [...target.scan.vulnerabilities].sort((a, b) => {
      const order = { CRITICAL: 0, HIGH: 1, MEDIUM: 2, LOW: 3 };
      return (order[a.severity] ?? 4) - (order[b.severity] ?? 4);
    });

    for (const vuln of sortedVulns) {
      patch += `--- FIX: ${vuln.id} [${vuln.severity}] ${vuln.title}\n`;
      patch += `+++ Location: ${vuln.location}\n\n`;

      // Generate specific fix code snippets
      const fix = generateFixSnippet(vuln, target);
      patch += fix;
      patch += `\n`;
    }

    // Security headers fix
    if (target.fingerprint?.securityHeaders?.missing?.length > 0) {
      patch += `--- FIX: Security Headers Configuration\n`;
      patch += `+++ Apply to: ${target.domain} (all subdomains)\n\n`;
      patch += generateHeadersFix(target);
      patch += `\n`;
    }

    patch += `\n`;
  }

  return patch;
}

/**
 * Generate a specific fix code snippet based on vulnerability type
 */
function generateFixSnippet(vuln, target) {
  const platform = target.fingerprint?.vibeStack?.platform || "Generic";
  let fix = "";

  switch (vuln.id) {
    case "VCC-001": // .env exposed
      fix += `# Step 1: Add .env to .gitignore (if not already)\n`;
      fix += `\`\`\`\n`;
      fix += `echo ".env" >> .gitignore\n`;
      fix += `echo ".env.local" >> .gitignore\n`;
      fix += `echo ".env.production" >> .gitignore\n`;
      fix += `\`\`\`\n\n`;
      fix += `# Step 2: Rotate ALL credentials in the exposed .env file immediately\n`;
      fix += `# - Database passwords\n`;
      fix += `# - API keys (Supabase, Stripe, etc.)\n`;
      fix += `# - Any secrets or tokens\n\n`;
      fix += `# Step 3: Move secrets to platform environment variables\n`;
      if (platform === "Vercel") {
        fix += `\`\`\`bash\nvercel env add SUPABASE_SERVICE_ROLE_KEY production\n\`\`\`\n`;
      } else if (platform === "Netlify") {
        fix += `\`\`\`bash\nnetlify env:set STRIPE_SECRET_KEY "sk_live_new_rotated_key"\n\`\`\`\n`;
      }
      break;

    case "VCC-002": // API key in client bundle
      fix += `# Step 1: Identify sensitive keys in your client code\n`;
      fix += `# Search for: SUPABASE_SERVICE_ROLE_KEY, STRIPE_SECRET, FIREBASE_ADMIN\n\n`;
      fix += `# Step 2: Move to server-side only\n`;
      fix += `\`\`\`javascript\n`;
      fix += `// ❌ BEFORE (in client-side code)\n`;
      fix += `// const supabase = createClient(url, process.env.NEXT_PUBLIC_SUPABASE_SERVICE_KEY)\n\n`;
      fix += `// ✅ AFTER (use anon key on client, service key only on server)\n`;
      fix += `// Client: use anon key + RLS\n`;
      fix += `const supabase = createClient(url, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY)\n\n`;
      fix += `// Server (API route / serverless function): use service role key\n`;
      fix += `const supabaseAdmin = createClient(url, process.env.SUPABASE_SERVICE_ROLE_KEY)\n`;
      fix += `\`\`\`\n`;
      break;

    case "VCC-003": // Open API without auth
      fix += `# Add authentication middleware to all API routes\n\n`;
      fix += `\`\`\`javascript\n`;
      fix += `// middleware/auth.js\n`;
      fix += `export function requireAuth(handler) {\n`;
      fix += `  return async (req, res) => {\n`;
      fix += `    const token = req.headers.authorization?.replace('Bearer ', '');\n`;
      fix += `    if (!token) {\n`;
      fix += `      return res.status(401).json({ error: 'Authentication required' });\n`;
      fix += `    }\n`;
      fix += `    try {\n`;
      fix += `      const user = await verifyToken(token);\n`;
      fix += `      req.user = user;\n`;
      fix += `      return handler(req, res);\n`;
      fix += `    } catch (err) {\n`;
      fix += `      return res.status(403).json({ error: 'Invalid token' });\n`;
      fix += `    }\n`;
      fix += `  };\n`;
      fix += `}\n`;
      fix += `\`\`\`\n`;
      break;

    case "VCC-007": // Supabase RLS
      fix += `# Enable Row Level Security on all tables\n\n`;
      fix += `\`\`\`sql\n`;
      fix += `-- Enable RLS\n`;
      fix += `ALTER TABLE volunteers ENABLE ROW LEVEL SECURITY;\n`;
      fix += `ALTER TABLE donations ENABLE ROW LEVEL SECURITY;\n`;
      fix += `ALTER TABLE sites ENABLE ROW LEVEL SECURITY;\n\n`;
      fix += `-- Create policies (example: users can only read their own data)\n`;
      fix += `CREATE POLICY "Users read own data" ON volunteers\n`;
      fix += `  FOR SELECT USING (auth.uid() = user_id);\n\n`;
      fix += `CREATE POLICY "Admins full access" ON volunteers\n`;
      fix += `  FOR ALL USING (auth.jwt() ->> 'role' = 'admin');\n`;
      fix += `\`\`\`\n`;
      break;

    case "VCC-008": // Firebase rules open
      fix += `# Update Firestore security rules\n\n`;
      fix += `\`\`\`javascript\n`;
      fix += `// firestore.rules\n`;
      fix += `rules_version = '2';\n`;
      fix += `service cloud.firestore {\n`;
      fix += `  match /databases/{database}/documents {\n`;
      fix += `    // ❌ BEFORE: allow read, write: if true;\n\n`;
      fix += `    // ✅ AFTER: Require authentication + role checks\n`;
      fix += `    match /cases/{caseId} {\n`;
      fix += `      allow read: if request.auth != null\n`;
      fix += `        && get(/databases/$(database)/documents/users/$(request.auth.uid)).data.role in ['admin', 'caseworker'];\n`;
      fix += `      allow write: if request.auth != null\n`;
      fix += `        && get(/databases/$(database)/documents/users/$(request.auth.uid)).data.role == 'admin';\n`;
      fix += `    }\n`;
      fix += `  }\n`;
      fix += `}\n`;
      fix += `\`\`\`\n`;
      break;

    default:
      fix += `# Remediation:\n`;
      fix += `# ${vuln.remediation}\n`;
      break;
  }

  return fix;
}

/**
 * Generate security headers configuration
 */
function generateHeadersFix(target) {
  const platform = target.fingerprint?.vibeStack?.platform || "Generic";
  let fix = "";

  if (platform === "Vercel") {
    fix += `# Add to vercel.json:\n`;
    fix += `\`\`\`json\n`;
    fix += `{\n`;
    fix += `  "headers": [\n`;
    fix += `    {\n`;
    fix += `      "source": "/(.*)",\n`;
    fix += `      "headers": [\n`;
    for (const h of target.fingerprint.securityHeaders.missing) {
      const value = getDefaultHeaderValue(h.name);
      fix += `        { "key": "${h.name}", "value": "${value}" },\n`;
    }
    fix += `      ]\n`;
    fix += `    }\n`;
    fix += `  ]\n`;
    fix += `}\n`;
    fix += `\`\`\`\n`;
  } else if (platform === "Netlify") {
    fix += `# Add to netlify.toml:\n`;
    fix += `\`\`\`toml\n`;
    fix += `[[headers]]\n`;
    fix += `  for = "/*"\n`;
    fix += `  [headers.values]\n`;
    for (const h of target.fingerprint.securityHeaders.missing) {
      const value = getDefaultHeaderValue(h.name);
      fix += `    ${h.name} = "${value}"\n`;
    }
    fix += `\`\`\`\n`;
  } else {
    fix += `# Add these headers to your server configuration:\n`;
    fix += `\`\`\`\n`;
    for (const h of target.fingerprint.securityHeaders.missing) {
      const value = getDefaultHeaderValue(h.name);
      fix += `${h.name}: ${value}\n`;
    }
    fix += `\`\`\`\n`;
  }

  return fix;
}

/**
 * Default recommended values for security headers
 */
function getDefaultHeaderValue(headerName) {
  const defaults = {
    "Strict-Transport-Security": "max-age=31536000; includeSubDomains; preload",
    "X-Content-Type-Options": "nosniff",
    "X-Frame-Options": "DENY",
    "Content-Security-Policy": "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'",
    "X-XSS-Protection": "1; mode=block",
    "Referrer-Policy": "strict-origin-when-cross-origin",
    "Permissions-Policy": "camera=(), microphone=(), geolocation=()"
  };
  return defaults[headerName] || "";
}

/**
 * Write all reports to disk
 */
export function writeReports(scoredTargets, outputDir) {
  const dir = outputDir || join(PROJECT_ROOT, "output");

  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }

  const reportPath = join(dir, "vibe-check-report.md");
  const patchPath = join(dir, "fix-artifact.patch");

  const report = generateVibeCheckReport(scoredTargets);
  const patch = generateFixArtifact(scoredTargets);

  writeFileSync(reportPath, report, "utf-8");
  writeFileSync(patchPath, patch, "utf-8");

  console.log(`📄 [REPORT] Written: ${reportPath}`);
  console.log(`🔧 [REPORT] Written: ${patchPath}`);

  return { reportPath, patchPath };
}
